Fixed logic error
Error: Was checking if ANY user existed already on the forum instead of the one that was trying to join.
Fix: Checked for the users id too instead of just the forum.